# Generated by Django 5.2.1 on 2025-06-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_alter_financialriskmodel_estimated_loss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertmodel',
            name='alert_type',
            field=models.CharField(choices=[('CLANDESTINE_SITE', 'Site clandestin détecté'), ('SITE_EXPANSION', "Expansion possible d'un site existant"), ('SUSPICIOUS_ACTIVITY', 'Activité suspecte détectée par IA'), ('NEW_SITE', "Nouveau site détecté près d'une rivière"), ('PROTECTED_ZONE_BREACH', 'Activité en zone protégée'), ('WATER_POLLUTION', "Pollution d'eau détectée"), ('DEFORESTATION_ALERT', 'Déforestation majeure détectée')], default='SUSPICIOUS_ACTIVITY', max_length=50),
        ),
        migrations.AlterField(
            model_name='alertmodel',
            name='level',
            field=models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé'), ('CRITICAL', 'Critique')], default='MEDIUM', max_length=20),
        ),
    ]
