# Generated by Django 5.2.1 on 2025-06-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_alter_investigationmodel_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionmodel',
            name='detection_type',
            field=models.CharField(choices=[('MINING_SITE', 'Site minier'), ('WATER_POLLUTION', 'Pollution eau'), ('DEFORESTATION', 'Déforestation'), ('SOIL_DISTURBANCE', 'Perturbation sol')], default='MINING_SITE', max_length=30),
        ),
        migrations.AlterField(
            model_name='detectionmodel',
            name='validation_status',
            field=models.CharField(choices=[('DETECTED', 'Détecté'), ('VALIDATED', 'Validé'), ('CONFIRMED', 'Confirmé'), ('FALSE_POSITIVE', 'Faux positif')], default='DETECTED', max_length=20),
        ),
    ]
