# Generated by Django 5.2.1 on 2025-06-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_reportmodel_file_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='report_type',
            field=models.CharField(choices=[('SUMMARY', 'Summary Report'), ('REGION_DETAIL', 'Regional Detail Report'), ('ALERT_SUMMARY', 'Alerts Summary Report'), ('DEFORESTATION_TREND', 'Deforestation Trend Report'), ('WATER_QUALITY_TREND', 'Water Quality Trend Report')], default='SUMMARY', help_text='Type of report generated', max_length=50),
        ),
    ]
