# Generated by Django 5.2.1 on 2025-06-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_alter_reportmodel_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardstatistic',
            name='statistic_type',
            field=models.CharField(choices=[('TOTAL_DETECTIONS', 'Total Detections'), ('ACTIVE_ALERTS', 'Active Alerts'), ('RESOLVED_ALERTS', 'Resolved Alerts'), ('NEW_MINING_SITES', 'New Mining Sites'), ('DEFORESTATION_HA', 'Total Deforestation (Ha)'), ('WATER_POLLUTION_INCIDENTS', 'Water Pollution Incidents'), ('VALIDATED_DETECTIONS', 'Validated Detections')], help_text='Type of aggregated statistic', max_length=50),
        ),
    ]
