# Generated by Django 5.2.1 on 2025-05-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionmodel',
            name='center_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='center_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
