# Generated by Django 5.2.1 on 2025-05-29 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0002_regionmodel_center_lat_regionmodel_center_lon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionmodel',
            name='geographic_zone',
        ),
    ]
